<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE archetypes [
		<!ELEMENT archetypes (archetype)*>
		<!ELEMENT archetype (title|description)*>
		<!ATTLIST archetype
				archetypeId CDATA #REQUIRED
				groupId CDATA #REQUIRED
				version CDATA #REQUIRED>
		<!ELEMENT title (#PCDATA)>
		<!ELEMENT description (#PCDATA)>
		]>
<archetypes>
	<archetype groupId="com.vaadin" version="7.6.3"
		archetypeId="vaadin-archetype-application">
		<title>Single-module Application Project</title>
		<description><![CDATA[A template FROM TEMPORARY SITE for a simple Vaadin application.
Puts everything in one module.]]></description>
	</archetype>
	<archetype groupId="com.vaadin" version="7.6.3"
		archetypeId="vaadin-archetype-application-multimodule">
		<title>Multi-module Application Project</title>
		<description><![CDATA[A template for a more complex Vaadin project.
Separates deployment, UI and widgetset into separate Maven modules.]]></description>
	</archetype>
	<archetype groupId="com.vaadin" version="7.6.3"
		archetypeId="vaadin-archetype-widget">
		<title>Add-on Project</title>
		<description><![CDATA[A multi-module widget add-on project for creating a re-usable Vaadin component, including a demo application.
Packages the add-on in a format ready to be deployed to Vaadin Directory.]]>
		</description>
	</archetype>
	<archetype groupId="com.vaadin" version="7.6.3"
		archetypeId="vaadin-archetype-application-example">
		<title>CRUD Example</title>
		<description><![CDATA[A multi-module example CRUD (create/read/update/delete) application containing a login screen, basic access control examples and more.
Provides a good example on how you can structure a Vaadin application.]]>
		</description>
	</archetype>
</archetypes>
